<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:sch="http://aeeph.com/routeservice" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://aeeph.com/routeservice" targetNamespace="http://aeeph.com/routeservice">
  <wsdl:types>
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://aeeph.com/routeservice">

    <!-- Complex Types -->
    <xs:complexType name="Coordinates">
        <xs:sequence>
            <xs:element minOccurs="0" name="x" type="xs:decimal"/>
            <xs:element name="y" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Location">
        <xs:sequence>
            <xs:element name="x" type="xs:double"/>
            <xs:element name="y" type="xs:double"/>
            <xs:element name="name" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="Priority">
        <xs:restriction base="xs:string">
            <xs:enumeration value="LOW"/>
            <xs:enumeration value="MEDIUM"/>
            <xs:enumeration value="HIGH"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="Route">
        <xs:sequence>
            <xs:element minOccurs="0" name="id" type="xs:long"/>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="coordinates" type="tns:Coordinates"/>
            <xs:element minOccurs="0" name="creationDate" type="xs:string"/>
            <xs:element name="from" type="tns:Location"/>
            <xs:element name="to" type="tns:Location"/>
            <xs:element minOccurs="0" name="distance" type="xs:int"/>
            <xs:element minOccurs="0" name="priority" type="tns:Priority"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="FilterEntry">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="key" type="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- GetRoutes -->
    <xs:element name="GetRoutesRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" name="sort" type="xs:string"/>
                <xs:element minOccurs="0" name="filters">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" minOccurs="0" name="filter" type="tns:FilterEntry"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element minOccurs="0" name="operations">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" minOccurs="0" name="operation" type="tns:FilterEntry"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element minOccurs="0" name="page" type="xs:int"/>
                <xs:element minOccurs="0" name="pageSize" type="xs:int"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="GetRoutesResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="totalCount" type="xs:long"/>
                <xs:element name="routes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" minOccurs="0" name="route" type="tns:Route"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- CreateRoute -->
    <xs:element name="CreateRouteRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="coordinates" type="tns:Coordinates"/>
                <xs:element name="from" type="tns:Location"/>
                <xs:element name="to" type="tns:Location"/>
                <xs:element minOccurs="0" name="distance" type="xs:int"/>
                <xs:element minOccurs="0" name="priority" type="tns:Priority"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="CreateRouteResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="route" type="tns:Route"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- GetRouteById -->
    <xs:element name="GetRouteByIdRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:long"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="GetRouteByIdResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="route" type="tns:Route"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- UpdateRoute -->
    <xs:element name="UpdateRouteRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:long"/>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="coordinates" type="tns:Coordinates"/>
                <xs:element name="from" type="tns:Location"/>
                <xs:element name="to" type="tns:Location"/>
                <xs:element minOccurs="0" name="distance" type="xs:int"/>
                <xs:element minOccurs="0" name="priority" type="tns:Priority"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="UpdateRouteResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="route" type="tns:Route"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- DeleteRoute -->
    <xs:element name="DeleteRouteRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:long"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="DeleteRouteResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="success" type="xs:boolean"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- GetMaxByFrom -->
    <xs:element name="GetMaxByFromRequest">
        <xs:complexType>
            <xs:sequence/>
        </xs:complexType>
    </xs:element>

    <xs:element name="GetMaxByFromResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="route" type="tns:Route"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- GetRoutesByNamePrefix -->
    <xs:element name="GetRoutesByNamePrefixRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="substring" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="GetRoutesByNamePrefixResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="routes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" minOccurs="0" name="route" type="tns:Route"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- GetUniqueDistances -->
    <xs:element name="GetUniqueDistancesRequest">
        <xs:complexType>
            <xs:sequence/>
        </xs:complexType>
    </xs:element>

    <xs:element name="GetUniqueDistancesResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="distances">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" minOccurs="0" name="distance" type="xs:int"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Error Response -->
    <xs:complexType name="ErrorDetail">
        <xs:sequence>
            <xs:element name="code" type="xs:int"/>
            <xs:element name="message" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>
  </wsdl:types>
  <wsdl:message name="DeleteRouteRequest">
    <wsdl:part element="tns:DeleteRouteRequest" name="DeleteRouteRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="GetRoutesByNamePrefixResponse">
    <wsdl:part element="tns:GetRoutesByNamePrefixResponse" name="GetRoutesByNamePrefixResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="GetRouteByIdRequest">
    <wsdl:part element="tns:GetRouteByIdRequest" name="GetRouteByIdRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="GetRoutesResponse">
    <wsdl:part element="tns:GetRoutesResponse" name="GetRoutesResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="CreateRouteResponse">
    <wsdl:part element="tns:CreateRouteResponse" name="CreateRouteResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="UpdateRouteResponse">
    <wsdl:part element="tns:UpdateRouteResponse" name="UpdateRouteResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="DeleteRouteResponse">
    <wsdl:part element="tns:DeleteRouteResponse" name="DeleteRouteResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="GetMaxByFromResponse">
    <wsdl:part element="tns:GetMaxByFromResponse" name="GetMaxByFromResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="GetMaxByFromRequest">
    <wsdl:part element="tns:GetMaxByFromRequest" name="GetMaxByFromRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="GetRoutesRequest">
    <wsdl:part element="tns:GetRoutesRequest" name="GetRoutesRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="GetUniqueDistancesResponse">
    <wsdl:part element="tns:GetUniqueDistancesResponse" name="GetUniqueDistancesResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="GetUniqueDistancesRequest">
    <wsdl:part element="tns:GetUniqueDistancesRequest" name="GetUniqueDistancesRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="GetRoutesByNamePrefixRequest">
    <wsdl:part element="tns:GetRoutesByNamePrefixRequest" name="GetRoutesByNamePrefixRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="CreateRouteRequest">
    <wsdl:part element="tns:CreateRouteRequest" name="CreateRouteRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="GetRouteByIdResponse">
    <wsdl:part element="tns:GetRouteByIdResponse" name="GetRouteByIdResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="UpdateRouteRequest">
    <wsdl:part element="tns:UpdateRouteRequest" name="UpdateRouteRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="RoutesPort">
    <wsdl:operation name="DeleteRoute">
      <wsdl:input message="tns:DeleteRouteRequest" name="DeleteRouteRequest">
    </wsdl:input>
      <wsdl:output message="tns:DeleteRouteResponse" name="DeleteRouteResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetRoutesByNamePrefix">
      <wsdl:input message="tns:GetRoutesByNamePrefixRequest" name="GetRoutesByNamePrefixRequest">
    </wsdl:input>
      <wsdl:output message="tns:GetRoutesByNamePrefixResponse" name="GetRoutesByNamePrefixResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetRouteById">
      <wsdl:input message="tns:GetRouteByIdRequest" name="GetRouteByIdRequest">
    </wsdl:input>
      <wsdl:output message="tns:GetRouteByIdResponse" name="GetRouteByIdResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetRoutes">
      <wsdl:input message="tns:GetRoutesRequest" name="GetRoutesRequest">
    </wsdl:input>
      <wsdl:output message="tns:GetRoutesResponse" name="GetRoutesResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="CreateRoute">
      <wsdl:input message="tns:CreateRouteRequest" name="CreateRouteRequest">
    </wsdl:input>
      <wsdl:output message="tns:CreateRouteResponse" name="CreateRouteResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="UpdateRoute">
      <wsdl:input message="tns:UpdateRouteRequest" name="UpdateRouteRequest">
    </wsdl:input>
      <wsdl:output message="tns:UpdateRouteResponse" name="UpdateRouteResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetMaxByFrom">
      <wsdl:input message="tns:GetMaxByFromRequest" name="GetMaxByFromRequest">
    </wsdl:input>
      <wsdl:output message="tns:GetMaxByFromResponse" name="GetMaxByFromResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetUniqueDistances">
      <wsdl:input message="tns:GetUniqueDistancesRequest" name="GetUniqueDistancesRequest">
    </wsdl:input>
      <wsdl:output message="tns:GetUniqueDistancesResponse" name="GetUniqueDistancesResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="RoutesPortSoap11" type="tns:RoutesPort">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="DeleteRoute">
      <soap:operation soapAction=""/>
      <wsdl:input name="DeleteRouteRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="DeleteRouteResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetRoutesByNamePrefix">
      <soap:operation soapAction=""/>
      <wsdl:input name="GetRoutesByNamePrefixRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="GetRoutesByNamePrefixResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetRouteById">
      <soap:operation soapAction=""/>
      <wsdl:input name="GetRouteByIdRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="GetRouteByIdResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetRoutes">
      <soap:operation soapAction=""/>
      <wsdl:input name="GetRoutesRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="GetRoutesResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="CreateRoute">
      <soap:operation soapAction=""/>
      <wsdl:input name="CreateRouteRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="CreateRouteResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="UpdateRoute">
      <soap:operation soapAction=""/>
      <wsdl:input name="UpdateRouteRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="UpdateRouteResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetMaxByFrom">
      <soap:operation soapAction=""/>
      <wsdl:input name="GetMaxByFromRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="GetMaxByFromResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetUniqueDistances">
      <soap:operation soapAction=""/>
      <wsdl:input name="GetUniqueDistancesRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="GetUniqueDistancesResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="RoutesPortService">
    <wsdl:port binding="tns:RoutesPortSoap11" name="RoutesPortSoap11">
      <soap:address location="https://127.0.0.1:27275/ws"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>