server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      uri: http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    routes-service:
      path: /api/v1/routes/**
      service-id: routes-service
    navigator-service:
      path: /api/v1/navigator/**
      service-id: navigator-service
  ignored-services: '*'