server:
  port: 27274
  ssl:
    enabled: false
    key-store: classpath:keystore.p12
    key-store-password: 1234
    key-store-type: PKCS12

routes:
  service:
    url: https://127.0.0.1:27297/api/v1/routes

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
