server:
  port: 8081

spring:
  application:
    name: navigator-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    ip-address: 192.168.101.243
    nonSecurePortEnabled: true
    nonSecurePort: 32412
    securePortEnabled: false
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${eureka.instance.nonSecurePort}
    statusPageUrl: http://${eureka.instance.ip-address}:${eureka.instance.nonSecurePort}/
    homePageUrl: http://${eureka.instance.ip-address}:${eureka.instance.nonSecurePort}/

routes:
  service:
    url: https://localhost:8765/api/v1/routes