server:
  port: 8081

spring:
  application:
    name: navigator-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

routes:
  service:
    url: http://routes-service/api/v1/routes