server:
  port: 8888
  ssl:
    enabled: false
    key-store: classpath:keystore.p12
    key-store-password: 1234
    key-store-type: PKCS12

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
  profiles:
    active: native

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
