server:
  port: 18080
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: 1234
    key-store-type: PKCS12

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

zuul:
  # prefix: /api
  routes:
    navigator-service:
      path: /api/v1/navigator/**
      serviceId: navigator-service
      stripPrefix: false
    routes-service:
      path: /**
      url: https://127.0.0.1:27297/
      stripPrefix: false

  ignored-services: '*'
  sslHostnameValidationEnabled: false

  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 10000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1

navigator-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList

routes-service:
  ribbon:
    TrustAllCertificates: true
    IsSecure: true
