server:
  port: 8765
  ssl:
    enabled: true
    key-store: classpath:keystore.p12      # ← имя вашего p12 в ресурсах
    key-store-type: PKCS12
    key-store-password: 1234              # ← ваш пароль
    # key-alias: gateway                   # укажите, если требуется
    # key-password: 1234                   # если отличается от key-store-password

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      uri: http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    routes-service:
      path: /api/v1/routes/**
      service-id: routes-service
    navigator-service:
      path: /api/v1/navigator/**
      service-id: navigator-service
  ignored-services: '*'

routes-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: https://localhost:27297
    IsSecure: true